# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Notable Integrations PoC
email: docs@sonatype.com
description: >- # this means to ignore newlines until "baseurl:"
  Major updates to Sonatype integrations. Find highlights here, with links to detailed changelogs. Subscribe via RSS for notifications.
baseurl: "/notable-integrations-poc" # the subpath of your site, e.g. /blog
url: "https://hernanpl.github.io/notable-integrations-poc" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

feed:
  path: /feed.xml # Customize the path if you want
  title: Notable Integrations
  description: Updates and releases for Sonatype Integrations
  language: en # Language of your content
  logo: /assets/logo.png
  icon: /assets/logo.png
  author: # Optional author information
    name: Sonatype
    email: docs@sonatype.com

collections:
  category:
    output: true
    permalink: /category/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
